version: '3'
services:
  backend:
    build: backend
    restart: on-failure
    environment:
      - FLASK_ENV=development

  frontend:
    build: frontend
    command: npm run start
    restart: on-failure
    depends_on:
      - "backend"
    ports:
      - 10001:3000

networks:
  default:
    external:
      name: printout
